### ISSUE TITLE
[ 5.3 PC Software Setup - Network Configuration ] Lack of information

### ISSUE THREAD

**Issue by Affonso-Gui** [ROBOTIS-GIT/turtlebot3_wiki#1]
In Turtlebot3 Tutorial section `5 PC Software Setup`, subsection `5.3 Network Configuration`, the following information are missing:

1. After introducing the `ifconfig` command, states 

> The rectangled text is the IP address of being used platform.

but nothing follows.

2. After saying to edit the .bashrc with `gedit ~/.bashrc`, states

>  Change the localhost into the IP address shown as follows.

 but nothing follows.

**Comment by ROBOTIS-Leon** [comment]
Check the fixes :)
