### ISSUE TITLE
[ Network Configuration ] Potentially misleading Image

### ISSUE THREAD

**Issue by Affonso-Gui** [ROBOTIS-GIT/turtlebot3_wiki#2]
Image in [turtlebot3_tutorials/docs/source/_static/software/network_configuration.png](https://github.com/ROBOTIS-GIT/turtlebot3_tutorials/blob/master/docs/source/_static/software/network_configuration.png) may lead to incorrect setups.

i.e. Assuming that [TurtleBot] refers to the Rasberry Pi included in Turtlebot3 Basic; and that [Remote PC] refers to another PC used in remote controlling, shouldn't the Master be set to [TurtleBot], to which the USB ports are connected to?

**Comment by ROBOTIS-Leon** [comment]
I think that ` the core should be in the Remote PC` to prevent run-away.
