### ISSUE TITLE
[ 10. SLAM ] Cannot launch SLAM from Raspberry Pi

### ISSUE THREAD

**Issue by Affonso-Gui** [ROBOTIS-GIT/turtlebot3_wiki#3]
When tried to launch `roslaunch turtlebot3_slam turtlebot3_slam.launch` from Raspberry Pi, got the following error message: 
```
core service [/rosout] found
process[robot_state_publisher-1]: started with pid [6587]

ERROR: cannot launch node of type [gmapping/slam_gmapping]: gmapping
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/turtlebot/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share
```
If really unable to launch from Raspberry Pi, might be a good idea to mention this on the Tutorial.

When connected the USB cables directly to my laptop, was able to launch SLAM but needed an additional `sudo chmod a+rw /dev/ttyACM0` before Bringup.

Runs normally when launching from remote PC (USB connected to Turtlebot's Raspberry Pi, as usual).

**Comment by robotpilot** [comment]
We have specified the following to prevent the confusion: In other words, the command you mentioned must be run on the remote PC.

[Remote PC] Open a terminal, then run the SLAM launch file.

**Comment by ROBOTIS-Leon** [comment]
`sudo chmod a+rw /dev/ttyACM0` would be typed anyway automatically.
`sudo chmod a+rw /dev/ttyUSBx` should be typed now manually, but will be added to be executed by `rule`

and the error that you showed can be occurred when the bringup in the TurtleBot3 is not launched
