### ISSUE TITLE
[ Alpha Test ] Problems with /turtlebot3_core

### ISSUE THREAD

**Issue by Affonso-Gui** [ROBOTIS-GIT/turtlebot3_wiki#4]
Here is Japan alpha tester. I am having troubles with /turtlebot3_core node, failing to publish data correctly.  More precisely, data from topics such as /odom and /joint_states does not get updated at all, even if Turtlebot moves. The topics are published and can be subscribed, /turtlebot3_core can also be pinged normally, but the values of position and velocity are always 0. 

I've done the OpenCR Setup according to the Tutorial, i.e.
> Setup OpenCR Board
>  Write bootloader with DFU_UTIL ( not quite sure if succeeded into running DFU mode, no feedback from board )
>  Write turtlebot3_core example firmware ( with AVRISP mkII , tried with DFU too with no success)

Still able to move the robot through topic, remote controller, teleop.
Checked Dynamixel with R+, seems to have no problems in hardware.

**Comment by robotpilot** [comment]
We sent you a microSD card with a tested OS image file. 
Please check if it is a new installation.

**Comment by Affonso-Gui** [comment]
If you mean the microSD in the Raspberry Pi, I had no trouble running Ubuntu 16 mate on it. Also tried connecting the USB cables directly into the laptop, but didn't solve.

In regard of the OpenCR firmware, I skipped the setup at first, but when I ran into the problem above tried to reinstall according to the tutorial. Even reinstalling no changes were observed.

The code I am using now is [here](https://github.com/ROBOTIS-GIT/OpenCR/tree/master/arduino/opencr_arduino/opencr/libraries/turtlebot3/turtlebot_basic/turtlebot3_core), and should be the latest one.

**Comment by Affonso-Gui** [comment]
Function Turtlebot3MotorDriver::readEncoder is returning false as dxl_getdata_result != true at `dxl_getdata_result = groupSyncRead.isAvailable(left_wheel_id_, addr, length); `

> [ID:001] groupSyncRead getdata failed

Being that
- left_wheel_id = 1
- addr  = 132
- lenght = 4

Below is full readEncoder source, from [turtlebot3_motor_driver.cpp](https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/turtlebot3/turtlebot_basic/turtlebot3_core/turtlebot3_motor_driver.cpp)
```
bool Turtlebot3MotorDriver::readEncoder(uint16_t addr, uint16_t length, int32_t &left_value, int32_t &right_value)
{
  int dxl_comm_result = COMM_TX_FAIL;              // Communication result
  bool dxl_addparam_result = false;                // addParam result
  bool dxl_getdata_result = false;                 // GetParam result

  dynamixel::GroupSyncRead groupSyncRead(portHandler_, packetHandler_, addr, length);

  // Set parameter
  dxl_addparam_result = groupSyncRead.addParam(left_wheel_id_);
  if (dxl_addparam_result != true)
  {
    // fprintf(stderr, "[ID:%03d] groupSyncRead addparam failed", left_wheel_id_);
    return false;
  }

  dxl_addparam_result = groupSyncRead.addParam(right_wheel_id_);
  if (dxl_addparam_result != true)
  {
    // fprintf(stderr, "[ID:%03d] groupSyncRead addparam failed", right_wheel_id_);
    return false;
  }

  // Syncread present position
  dxl_comm_result = groupSyncRead.txRxPacket();
  if (dxl_comm_result != COMM_SUCCESS) packetHandler_->printTxRxResult(dxl_comm_result);

  // Check if groupsyncread data of Dynamixels are available
  dxl_getdata_result = groupSyncRead.isAvailable(left_wheel_id_, addr, length);
  if (dxl_getdata_result != true)
  {
    // fprintf(stderr, "[ID:%03d] groupSyncRead getdata failed", left_wheel_id_);
    return false;
  }

  dxl_getdata_result = groupSyncRead.isAvailable(right_wheel_id_, addr, length);
  if (dxl_getdata_result != true)
  {
    // fprintf(stderr, "[ID:%03d] groupSyncRead getdata failed", right_wheel_id_);
    return false;
  }

  // Get data
  left_value  = groupSyncRead.getData(left_wheel_id_,  addr, length);
  right_value = groupSyncRead.getData(right_wheel_id_, addr, length);

  return true;
}
```

**Comment by Affonso-Gui** [comment]
When tested with `read4ByteTxRx`, returned the following error message (dxl_comm_result = COMM_RX_TIMEOUT):
> [TxRxResult] There is no status packet!

When connected the Dynamixel directly with USB2Dynamixel worked normally, being able to read and write both from R+ Manager and from sample c++ source.

Had the same problem when connected other Dynamixel units to the OpenCR, so the problem does really seem to be with the OpenCR board.

Also tested sending goal velocity with `write4ByteTxRx`, which succeeded on spinning the wheel, but dxl_comm_result returned the same COMM_RX_TIMEOUT.

What should I do?

**Comment by ROBOTIS-Leon** [comment]
1. More precisely, data from topics such as /odom and /joint_states does not get updated at all, even if Turtlebot moves. The topics are published and can be subscribed, /turtlebot3_core can also be pinged normally, but the values of position and velocity are always 0.

``` bash
Does TB3 still make problem? We perhaps should specify each cases like:
1) /odom issue: please update the latest OpenCR firmware again, and see how it works.
2) /joint_states: Try `broadcast ping` in the example of the OpenCR called <kbd>dxl_monitor</kbd>. If it cant detect 2 Dynamixels, maybe the problem is in the OpenCR board. Tell us if it is so that we can give you extra one.
```

2. Setup OpenCR Board
Write bootloader with DFU_UTIL ( not quite sure if succeeded into running DFU mode, no feedback from board )
Write turtlebot3_core example firmware ( with AVRISP mkII , tried with DFU too with no success)

``` bash
Keep trying with DFU_UTIL. Once you finished uploading the bootloader, press <kbd>reset</kbd> button on the OpenCR (the biggest one of 4 buttons)
```

3. If you mean the microSD in the Raspberry Pi, I had no trouble running Ubuntu 16 mate on it. Also tried connecting the USB cables directly into the laptop, but didn't solve.

In regard of the OpenCR firmware, I skipped the setup at first, but when I ran into the problem above tried to reinstall according to the tutorial. Even reinstalling no changes were observed.

The code I am using now is here, and should be the latest one.

``` bash
The image is updated to new one. Take it, and give us further feedbacks
```

4. Function Turtlebot3MotorDriver::readEncoder ~ What should I do?

``` bash
Try following the instruction written in 1.
```

**Comment by Affonso-Gui** [comment]
Updated the OpenCR firmware to version 1.0.8, but the problem persists, returning
```
[INFO] [1489383108.132117]: foo = 0
```
on execution. Still able to write through publishing in /cmd_vel ; keyboard teleop etc. , but unable to read data from dynamixel. When closing `rostopic echo /joint_state` get a 
```
[WARN] [1489370500.957018]: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
```

Examples->DynamixelSDK->protocol2.0->dxl_monitor returns
```
***********************************************************************
*                            DXL Monitor                              *
***********************************************************************

Succeeded to open the port!

 - Device Name : /dev/ACM0

 - Baudrate    : 1000000

Be sure to enable Carriage return
[CMD] scan

Scan Dynamixel Using Protocol 1.0
............................................................................................................................................................................................................................................................

Scan Dynamixel Using Protocol 2.0
............................................................................................................................................................................................................................................................

[CMD] ping 1 2 

ping Using Protocol 1.0

                                          ... FAIL 
 [ID:001] 

                                          ... FAIL 
 [ID:002] 


ping Using Protocol 2.0

                                          ... FAIL 
 [ID:001] 

                                          ... FAIL 
 [ID:002] 

[CMD] bp

[CMD] 
```

Examples->DynamixelSDK->protocol2.0->broadcast_ping returns
```
Start..
Succeeded to open the port!
Succeeded to change the baudrate!
Detected Dynamixel : 
```

Examples->DynamixelSDK->protocol2.0->ping returns
```
Start..
Succeeded to open the port!
Succeeded to change the baudrate!
ID : 1 ModelNumber : 0
ID : 2 ModelNumber : 0
```

Seems to be a problem in OpenCR board...
